{% set name = "ducc0" %}
{% set version = "0.20.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ducc0-{{ version }}.tar.gz
  sha256: 97ce2380b044f85022924beb989316ac0474459c4dcca3c8ea9f99a2eaf67107

build:
  number: 0
  skip: true  # [py<=36]
  script_env: DUCC0_OPTIMIZATION=portable
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - pybind11
    - python
  run:
    - numpy >=1.17.0
    - python

test:
  imports:
    - ducc0
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.mpcdf.mpg.de/mtr/ducc
  summary: Distinctly useful code collection
  license: GPL-2.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ickc
